### ISSUE TITLE
Research libraries for Python App GUI.

### ISSUE THREAD

**Issue by BespokeFire** [li-johnny/colony-capstone#33]

**Comment by li-johnny** [comment]
### Kivy

**Pros**
- Extensive video guides exist on [youtube](https://www.youtube.com/playlist?list=PLCC34OHNcOtpz7PJQ7Tv7hqFBP_xDDjqg)
- Great for small-scale projects and styling UI
- Does not require internet connection
- Supports Windows, MacOS, IOS, and Android

**Cons**
- Can have a steep learning curve
- Not the best option for mobile UI applications
- Requires PyInstaller to convert to executable (will trigger Windows virus warning)

**Comment by li-johnny** [comment]
### Tkinter
**Pros**

- Simple and easy to build UI
- Already built-in to standard Python Library
- Extensive documentation and video guides exist 
- Supports Windows and MacOS

**Cons**

- Requires serious effort to style (like the HTML of UI styling)
- Limited limited library of features
- No built-in UI designer
- Requires PyInstaller to convert to executable (will trigger Windows virus warning)
- Does not support mobile device UI

**Comment by li-johnny** [comment]
### Qt ([pyQt6 or pyside6](https://www.pythonguis.com/faq/pyqt6-vs-pyside6/))

**Pros**

- Powerful UI designing capabilities
- Supports Windows, MacOS, IOS, and Android
- Has UI designer capabilities (able to drag and drop widgets and features)

**Cons**

- Seamless integration to IOS and Android UI will be more difficult than Kivy (either option is still difficult)
- Requires PyInstaller to convert to executable (will trigger Windows virus warning)
- Steep learning curve

**Comment by li-johnny** [comment]
### Electron

**Pros**

- Can integrate with existing web development to build a desktop application (i.e. Discord)
- Supports Windows and MacOS
- Extensive documentation and video guides exist on par with Kivy
- Essentially a browser and server in one

**Cons**

- Can be awkward to build a web app that only runs for desktop purposes
- Hardware resource intensive
- Large package size and boot-up time
